export const SET_PLACES_TREE = "SET_PLACES_TREE";
export const SET_INVENTORIES = "SET_INVENTORIES";
export const SET_PLACES_LOADING = "SET_PLACES_LOADING";
export const SET_PLACES_LOADING_ERROR = "SET_PLACES_LOADING_ERROR";
export const SET_INVENTORIES_LOADING = "SET_INVENTORIES_LOADING";
export const SET_INVENTORIES_LOADING_ERROR = "SET_PLACES_LOADING_ERROR";
